proxy:
  test_url: "http://httpbin.org/ip"
  max_workers: 4
  request_timeout: 10
  max_delay_ms: 900
  ttl: 86400  # Proxy validity in seconds (1 day)
  ip_api_concurrency: 45  # Max concurrent IP-API requests
  test_url: https://api.ipify.org?format=json
scraper:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  timeout: 5
  urls:
    - "https://www.freeproxy.world/?type=http&anonymity=&country=&speed=&port=&page=1"
    - "https://proxycompass.com/ru/free-proxy/"
    - "https://www.ssl froxies.org/"
    - "https://free-proxy-list.net/"
database:
  file: "proxies.db"
logging:
  file: "proxy_checker.log"
backup_proxies:
  file: "backup_proxies.json"